// swift-tools-version: 6.2
import PackageDescription

// Generado por `archinit --multi` (PRD-AF-10). Domain: modelos/protocolos compartidos,
// solo Foundation. Un <Cap>Kit por --capability, un <Sdk>Adapters por --adapter — cada
// uno implementa un protocolo de Domain; `.archlint.yml` (raíz, R13) impide que un
// Kit/Adapter importe otro, o que una feature importe cualquiera de los dos.
let swiftSettings: [SwiftSetting] = [
    .defaultIsolation(MainActor.self),
    .enableUpcomingFeature("InferIsolatedConformances"),
    .enableUpcomingFeature("NonisolatedNonsendingByDefault")
]

let package = Package(
    name: "Platform",
    platforms: [
        .iOS(.v17),
        .macOS(.v14)
    ],
    products: [
        .library(name: "Domain", targets: ["Domain"]),
        .library(name: "Networking", targets: ["Networking"]),
        .library(name: "CameraKit", targets: ["CameraKit"]),
        .library(name: "AnalyticsAdapters", targets: ["AnalyticsAdapters"]),
        // Test-only, like `AppFoundationTestSupport`: mocks/spies shared by more than one
        // `*FeatureTests` target in `Packages/Features` (PRD-APP-02, Fase 1) — a regular
        // library product, not a `.testTarget`, because a `.testTarget`'s products aren't
        // importable from another package.
        .library(name: "PlatformTestSupport", targets: ["PlatformTestSupport"])
    ],
    dependencies: [
        .package(url: "https://github.com/hiramvazquez/AppFoundation.git", from: "1.2.3"),
        .package(url: "https://github.com/hiramvazquez/CoreNetworking.git", from: "1.0.0")
    ],
    targets: [
        .target(
            name: "Domain",
            path: "Sources/Domain",
            swiftSettings: swiftSettings,
            plugins: [.plugin(name: "ArchitectureLint", package: "AppFoundation")]
        ),
        .testTarget(
            name: "DomainTests",
            dependencies: ["Domain"],
            path: "Tests/DomainTests",
            swiftSettings: swiftSettings
        ),
        // Not generated by `archinit --multi` — added by hand (PRD-APP-02, Fase 1):
        // everything cross-cutting about networking/session that needs CoreNetworking
        // (`Domain` only imports `Foundation`) but is shared by more than one feature
        // (`AuthServicing`/`ProductsServicing`) or is pure app-wide composition
        // (`NetworkingModule`, `AppSessionState`) tied to the authenticated
        // `APIServiceProtocol` this target builds.
        .target(
            name: "Networking",
            dependencies: [
                "Domain",
                .product(name: "AppFoundation", package: "AppFoundation"),
                .product(name: "CoreNetworking", package: "CoreNetworking")
            ],
            path: "Sources/Networking",
            swiftSettings: swiftSettings,
            plugins: [.plugin(name: "ArchitectureLint", package: "AppFoundation")]
        ),
        .testTarget(
            name: "NetworkingTests",
            dependencies: [
                "Networking",
                "PlatformTestSupport",
                .product(name: "AppFoundationTestSupport", package: "AppFoundation"),
                .product(name: "CoreNetworkingTestSupport", package: "CoreNetworking")
            ],
            path: "Tests/NetworkingTests",
            swiftSettings: swiftSettings
        ),
        .target(
            name: "PlatformTestSupport",
            dependencies: [
                "Domain",
                "Networking",
                .product(name: "AppFoundationTestSupport", package: "AppFoundation"),
                .product(name: "CoreNetworking", package: "CoreNetworking")
            ],
            path: "Sources/PlatformTestSupport",
            swiftSettings: swiftSettings
        ),
        .target(
            name: "CameraKit",
            dependencies: ["Domain"],
            path: "Sources/CameraKit",
            swiftSettings: swiftSettings,
            plugins: [.plugin(name: "ArchitectureLint", package: "AppFoundation")]
        ),
        .target(
            name: "AnalyticsAdapters",
            dependencies: ["Domain"],
            path: "Sources/AnalyticsAdapters",
            swiftSettings: swiftSettings,
            plugins: [.plugin(name: "ArchitectureLint", package: "AppFoundation")]
        )
    ]
)
